name: Azure Static Web Apps CI/CD -dev-

on:
  push:
    branches:
      - main
      - dev
      - stage

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev
      - stage

# steps:
# - powershell: |
#     New-Item -Path $(System.DefaultWorkingDirectory) -Name "env.json" -Force -Value @'
#     {
#     "REACT_APP_SOMW_KEY": "$(REACT_APP_SOMW_KEY)",
#     }
#     '@
#     Get-Content -Path $(System.DefaultWorkingDirectory)\env.json
#     Get-ChildItem -Path $(System.DefaultWorkingDirectory)
#   displayName: 'Create "env.json" file'

env:
  REACT_APP_API_KEY: ${{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}}
  REACT_APP_API_ENV: ${{prod}}

#   // base API url
# REACT_APP_API_URL=https://metricmate-api-dev.azurewebsites.net
# REACT_APP_API_BASE_URL=/metricmate/mm-webapi/v0

# // firebase
# REACT_APP_API_KEY_FIREBASE_=AIzaSyAbTVToEBsFNI0poIsvsPPrhsBJAU0ueKo
# REACT_APP_API_FIREBASE_DOMAIN=metric-mate.firebaseapp.com
# REACT_APP_API_FIREBASE_DB_URL=https://metric-mate.firebaseio.com
# REACT_APP_API_FIREBASE_PROJECT_ID=metric-mate
# REACT_APP_API_FIREBASE_STORE_BUCKET=metric-mate.appspot.com
# REACT_APP_API_FIREBASE_SENDER_ID=559661309646
# REACT_APP_API_FIREBASE_APP_ID=1:559661309646:web:83d5fbb27d483a872e3a9f
# REACT_APP_API_FIREBASE_MEASUREMENT_ID=G-24LVR5TX8P


jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:      
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_WATER_01DAAFE10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          deployment_environment: "dev"
          production_branch: "main"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_WATER_01DAAFE10 }}
          action: "close"      